config/routes.rb
Rails.application.routes.draw do
  resources :orders

  root 'orders#index'

end

app/models/concerns/is_selectable.rb
module IsSelectable
  extend ActiveSupport::Concern

  included do
    has_many :order_items, as: :itemable
    attr_accessor :is_selected, :quantity, :order_item_id
  end

  def decorate_selection_and_quantity(order)
    oi = order.order_items.where(itemable: self).first
    return unless oi.present?
    self.quantity = oi.quantity
    self.order_item_id = oi.id
    self.is_selected = true
  end

  def selectable_json
    {
      id: id,
      name: name,
      name_to_s: name_to_s,
      amount_cents: amount_cents,
      allowMultiple: allow_multiple,
      maxQuantity: max_quantity.present? ? max_quantity : 1,
      isChecked: is_selected.present? ? is_selected : false,
      orderItemId: order_item_id.present? ? order_item_id : nil,
      quantity: quantity.present? ? quantity : 1
    }
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :item_variations
  include IsSelectable

  def name_to_s
    name
  end

  def as_json(options=nil)
    selectable_json.merge(
      {
        item_id: id,
        itemable_type: 'Item',
        hasVariations: item_variations.present?
      }
    )
  end
end

app/models/item_variation.rb
class ItemVariation < ActiveRecord::Base
  belongs_to :item
  include IsSelectable

  def name_to_s
    "#{item.name} - #{name}"
  end

  def as_json(options=nil)
    selectable_json.merge(
      {
        item_id: item_id,
        itemable_type: 'ItemVariation',
        hasVariations: false,
      }
    )
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items, allow_destroy: true

  monetize :total_cost_cents

  def total_cost_cents
    order_items.map(&:cost_cents).sum
  end

  def items_for_order
    items = []
    Item.all.includes(:item_variations).each do |i|
      i.item_variations.each do |iv|
        iv.decorate_selection_and_quantity(self)
        i.is_selected = true if iv.is_selected
        items << iv
      end
      i.decorate_selection_and_quantity(self)
      items << i
    end
    items
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :itemable, polymorphic: true
  delegate :name, :name_to_s, to: :itemable
  validates_presence_of :itemable_id, :itemable_type
  before_save :assign_cost
  monetize :cost_cents

  def cost_cents
    quantity * cost_each_cents
  end

  def name_to_s
    "#{itemable.name_to_s}#{quantity_to_s}"
  end

  def quantity_to_s
    if quantity.present? && quantity > 1
      " x #{quantity}"
    end
  end

  private

  def assign_cost
    self.cost_each_cents = itemable.amount_cents
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      permits = [order_items_attributes: [:id, :order_id, :quantity, :itemable_id, :itemable_type, :_destroy]]
      params[:order].permit(permits)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactFluxRailsDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">React/Flux/Rails Demo</a>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div><!-- /.container -->
</body>
</html>

app/views/orders/_form.html.slim
- if @order.errors.any?
  #error_explanation
    h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
    ul
      - @order.errors.full_messages.each do |message|
        li = message

.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        .panel-title
          | Books
      .panel-body
        = react_component("App.SelectionList", selections: @order.items_for_order)
  .col-md-6
    .panel.panel-default
      .panel-heading
        .panel-title
          | Shopping Cart
      .panel-body
        = react_component("App.SelectedSelectionsList", {} )

= form_for @order do |f|
  = react_component("App.SelectionsForForm", {} )
  = f.submit 'Save', class: 'btn btn-primary'

app/views/orders/edit.html.slim
h2 Editing order

== render 'form'

app/views/orders/index.html.slim
h2 Orders

table.table.table-striped.table-bordered
  thead
    tr
      th #
      th Items
      th Total

  tbody
    - @orders.each do |order|
      tr
        td = link_to "##{order.id}", order
        td = order.order_items.map(&:name_to_s).to_sentence
        td = humanized_money_with_symbol(order.total_cost)

br

= link_to 'New Order', new_order_path, class: 'btn btn-default'

app/views/orders/new.html.slim
h2 New order

== render 'form'

app/views/orders/show.html.slim
.panel.panel-default
  .panel-heading ##{@order.id}
  table.table.table-striped.table-bordered
    thead
      tr
        th Item
        th Cost

    tbody
      - @order.order_items.each do |oi|
        tr
          td = oi.name_to_s
          td = humanized_money_with_symbol(oi.cost)

p
  = link_to 'Edit', edit_order_path(@order), class: 'btn btn-default'
  = link_to 'Destroy', @order, class: 'btn', data: {:confirm => 'Are you sure?'}, :method => :delete